# 1) Bootstrap only
- hosts: all
  connection: docker
  gather_facts: no
  tasks:
    

    - name: Install python packages needed for Ansible
      raw: |
       apt-get update --fix-missing
       apt-get install -y python3 python3-apt python3-six


# 2) Real configuration after Python is installed
- hosts: all
  connection: docker
  gather_facts: no
  roles:
    - common

- hosts: webservers
  connection: docker
  roles:
    - webserver

- hosts: loadbalancer
  connection: docker
  roles:
    - loadbalancer

- hosts: dbservers
  connection: docker
  roles:
    - mysqlserver
