$ANSIBLE_VAULT;1.1;AES256
35376564303030613234636463303165626238623362616166383637613336343534663935333632
6534313665333638316138663164346162306436346238650a323338323833353633376630626531
62643366653035303933366361386565613463643634363163393465363161353239656230306331
3930356664353837350a626135653637316333363738393033353465626630646331356263353136
30326330353931643736373430646339323639376634323535616163646332316539633863633062
39373431346266313834666561343039343562356438633163333133616161303062363035313833
39623837396534346233346362653839346338306531613265333934343234353063326263656237
61633734636337373934666564633331663764623165643233396666363362346435353332326365
64653066643162663163663838396637656532333164393237343638366532626339323031393034
32383034333632643462303636323537613431316566343365323931396662633738643534306232
66663730613638343434616433363166343661326337623535616538333133386636343034393061
61383237353335373633
