- name: Install NGINX
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Deploy LB config
  template:
    src: lb.conf.j2
    dest: /etc/nginx/sites-available/lb.conf

- name: Enable site
  file:
    src: /etc/nginx/sites-available/lb.conf
    dest: /etc/nginx/sites-enabled/lb.conf
    state: link
  notify: restart nginx
